/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/* pa00_gpio */
#define PA00_GPIO \
	SAM_PINMUX(a, 0, gpio, gpio)

/* pa00a_can0_tx */
#define PA00A_CAN0_TX \
	SAM_PINMUX(a, 0, a, periph)

/* pa00b_pwm_pwml3 */
#define PA00B_PWM_PWML3 \
	SAM_PINMUX(a, 0, b, periph)

/* pa01_gpio */
#define PA01_GPIO \
	SAM_PINMUX(a, 1, gpio, gpio)

/* pa01a_can0_rx */
#define PA01A_CAN0_RX \
	SAM_PINMUX(a, 1, a, periph)

/* pa01b_pmc_pck0 */
#define PA01B_PMC_PCK0 \
	SAM_PINMUX(a, 1, b, periph)

/* pa01x_supc_wkup0 */
#define PA01X_SUPC_WKUP0 \
	SAM_PINMUX(a, 1, x, extra)

/* pa02_gpio */
#define PA02_GPIO \
	SAM_PINMUX(a, 2, gpio, gpio)

/* pa02a_tc0_tioa1 */
#define PA02A_TC0_TIOA1 \
	SAM_PINMUX(a, 2, a, periph)

/* pa02b_ebi_nandrdy */
#define PA02B_EBI_NANDRDY \
	SAM_PINMUX(a, 2, b, periph)

/* pa02x_adc_ad0 */
#define PA02X_ADC_AD0 \
	SAM_PINMUX(a, 2, x, extra)

/* pa03_gpio */
#define PA03_GPIO \
	SAM_PINMUX(a, 3, gpio, gpio)

/* pa03a_tc0_tiob1 */
#define PA03A_TC0_TIOB1 \
	SAM_PINMUX(a, 3, a, periph)

/* pa03b_pwm_pwmfi1 */
#define PA03B_PWM_PWMFI1 \
	SAM_PINMUX(a, 3, b, periph)

/* pa03x_adc_ad1 */
#define PA03X_ADC_AD1 \
	SAM_PINMUX(a, 3, x, extra)

/* pa03x_supc_wkup1 */
#define PA03X_SUPC_WKUP1 \
	SAM_PINMUX(a, 3, x, extra)

/* pa04_gpio */
#define PA04_GPIO \
	SAM_PINMUX(a, 4, gpio, gpio)

/* pa04a_tc0_tclk1 */
#define PA04A_TC0_TCLK1 \
	SAM_PINMUX(a, 4, a, periph)

/* pa04b_ebi_nwait */
#define PA04B_EBI_NWAIT \
	SAM_PINMUX(a, 4, b, periph)

/* pa04x_adc_ad2 */
#define PA04X_ADC_AD2 \
	SAM_PINMUX(a, 4, x, extra)

/* pa05_gpio */
#define PA05_GPIO \
	SAM_PINMUX(a, 5, gpio, gpio)

/* pa05a_tc0_tioa2 */
#define PA05A_TC0_TIOA2 \
	SAM_PINMUX(a, 5, a, periph)

/* pa05b_pwm_pwmfi0 */
#define PA05B_PWM_PWMFI0 \
	SAM_PINMUX(a, 5, b, periph)

/* pa05x_supc_wkup2 */
#define PA05X_SUPC_WKUP2 \
	SAM_PINMUX(a, 5, x, extra)

/* pa06_gpio */
#define PA06_GPIO \
	SAM_PINMUX(a, 6, gpio, gpio)

/* pa06a_tc0_tiob2 */
#define PA06A_TC0_TIOB2 \
	SAM_PINMUX(a, 6, a, periph)

/* pa06b_ebi_ncs0 */
#define PA06B_EBI_NCS0 \
	SAM_PINMUX(a, 6, b, periph)

/* pa06x_adc_ad3 */
#define PA06X_ADC_AD3 \
	SAM_PINMUX(a, 6, x, extra)

/* pa07_gpio */
#define PA07_GPIO \
	SAM_PINMUX(a, 7, gpio, gpio)

/* pa07a_tc0_tclk2 */
#define PA07A_TC0_TCLK2 \
	SAM_PINMUX(a, 7, a, periph)

/* pa07b_ebi_ncs1 */
#define PA07B_EBI_NCS1 \
	SAM_PINMUX(a, 7, b, periph)

/* pa07x_supc_wkup3 */
#define PA07X_SUPC_WKUP3 \
	SAM_PINMUX(a, 7, x, extra)

/* pa08_gpio */
#define PA08_GPIO \
	SAM_PINMUX(a, 8, gpio, gpio)

/* pa08a_uart_rxd */
#define PA08A_UART_RXD \
	SAM_PINMUX(a, 8, a, periph)

/* pa08b_pwm_pwmh0 */
#define PA08B_PWM_PWMH0 \
	SAM_PINMUX(a, 8, b, periph)

/* pa08x_supc_wkup4 */
#define PA08X_SUPC_WKUP4 \
	SAM_PINMUX(a, 8, x, extra)

/* pa09_gpio */
#define PA09_GPIO \
	SAM_PINMUX(a, 9, gpio, gpio)

/* pa09a_uart_txd */
#define PA09A_UART_TXD \
	SAM_PINMUX(a, 9, a, periph)

/* pa09b_pwm_pwmh3 */
#define PA09B_PWM_PWMH3 \
	SAM_PINMUX(a, 9, b, periph)

/* pa10_gpio */
#define PA10_GPIO \
	SAM_PINMUX(a, 10, gpio, gpio)

/* pa10a_usart0_rxd */
#define PA10A_USART0_RXD \
	SAM_PINMUX(a, 10, a, periph)

/* pa10b_dacc_datrg */
#define PA10B_DACC_DATRG \
	SAM_PINMUX(a, 10, b, periph)

/* pa10x_supc_wkup5 */
#define PA10X_SUPC_WKUP5 \
	SAM_PINMUX(a, 10, x, extra)

/* pa11_gpio */
#define PA11_GPIO \
	SAM_PINMUX(a, 11, gpio, gpio)

/* pa11a_usart0_txd */
#define PA11A_USART0_TXD \
	SAM_PINMUX(a, 11, a, periph)

/* pa11b_adc_adtrg */
#define PA11B_ADC_ADTRG \
	SAM_PINMUX(a, 11, b, periph)

/* pa11x_supc_wkup6 */
#define PA11X_SUPC_WKUP6 \
	SAM_PINMUX(a, 11, x, extra)

/* pa12_gpio */
#define PA12_GPIO \
	SAM_PINMUX(a, 12, gpio, gpio)

/* pa12a_usart1_rxd */
#define PA12A_USART1_RXD \
	SAM_PINMUX(a, 12, a, periph)

/* pa12b_pwm_pwml1 */
#define PA12B_PWM_PWML1 \
	SAM_PINMUX(a, 12, b, periph)

/* pa12x_supc_wkup7 */
#define PA12X_SUPC_WKUP7 \
	SAM_PINMUX(a, 12, x, extra)

/* pa13_gpio */
#define PA13_GPIO \
	SAM_PINMUX(a, 13, gpio, gpio)

/* pa13a_usart1_txd */
#define PA13A_USART1_TXD \
	SAM_PINMUX(a, 13, a, periph)

/* pa13b_pwm_pwmh2 */
#define PA13B_PWM_PWMH2 \
	SAM_PINMUX(a, 13, b, periph)

/* pa14_gpio */
#define PA14_GPIO \
	SAM_PINMUX(a, 14, gpio, gpio)

/* pa14a_usart1_rts */
#define PA14A_USART1_RTS \
	SAM_PINMUX(a, 14, a, periph)

/* pa14b_ssc_tk */
#define PA14B_SSC_TK \
	SAM_PINMUX(a, 14, b, periph)

/* pa15_gpio */
#define PA15_GPIO \
	SAM_PINMUX(a, 15, gpio, gpio)

/* pa15a_usart1_cts */
#define PA15A_USART1_CTS \
	SAM_PINMUX(a, 15, a, periph)

/* pa15b_ssc_tf */
#define PA15B_SSC_TF \
	SAM_PINMUX(a, 15, b, periph)

/* pa15x_supc_wkup8 */
#define PA15X_SUPC_WKUP8 \
	SAM_PINMUX(a, 15, x, extra)

/* pa16_gpio */
#define PA16_GPIO \
	SAM_PINMUX(a, 16, gpio, gpio)

/* pa16a_spi1_spck1 */
#define PA16A_SPI1_SPCK1 \
	SAM_PINMUX(a, 16, a, periph)

/* pa16b_ssc_td */
#define PA16B_SSC_TD \
	SAM_PINMUX(a, 16, b, periph)

/* pa16x_adc_ad7 */
#define PA16X_ADC_AD7 \
	SAM_PINMUX(a, 16, x, extra)

/* pa17_gpio */
#define PA17_GPIO \
	SAM_PINMUX(a, 17, gpio, gpio)

/* pa17a_twi0_twd */
#define PA17A_TWI0_TWD \
	SAM_PINMUX(a, 17, a, periph)

/* pa17b_spi0_spck0 */
#define PA17B_SPI0_SPCK0 \
	SAM_PINMUX(a, 17, b, periph)

/* pa18_gpio */
#define PA18_GPIO \
	SAM_PINMUX(a, 18, gpio, gpio)

/* pa18a_twi0_twck */
#define PA18A_TWI0_TWCK \
	SAM_PINMUX(a, 18, a, periph)

/* pa18b_ebi_a20 */
#define PA18B_EBI_A20 \
	SAM_PINMUX(a, 18, b, periph)

/* pa18x_supc_wkup9 */
#define PA18X_SUPC_WKUP9 \
	SAM_PINMUX(a, 18, x, extra)

/* pa19_gpio */
#define PA19_GPIO \
	SAM_PINMUX(a, 19, gpio, gpio)

/* pa19a_hsmci_mcck */
#define PA19A_HSMCI_MCCK \
	SAM_PINMUX(a, 19, a, periph)

/* pa19b_pwm_pwmh1 */
#define PA19B_PWM_PWMH1 \
	SAM_PINMUX(a, 19, b, periph)

/* pa20_gpio */
#define PA20_GPIO \
	SAM_PINMUX(a, 20, gpio, gpio)

/* pa20a_hsmci_mccda */
#define PA20A_HSMCI_MCCDA \
	SAM_PINMUX(a, 20, a, periph)

/* pa20b_pwm_pwml2 */
#define PA20B_PWM_PWML2 \
	SAM_PINMUX(a, 20, b, periph)

/* pa21_gpio */
#define PA21_GPIO \
	SAM_PINMUX(a, 21, gpio, gpio)

/* pa21a_hsmci_mcda0 */
#define PA21A_HSMCI_MCDA0 \
	SAM_PINMUX(a, 21, a, periph)

/* pa21b_pwm_pwml0 */
#define PA21B_PWM_PWML0 \
	SAM_PINMUX(a, 21, b, periph)

/* pa22_gpio */
#define PA22_GPIO \
	SAM_PINMUX(a, 22, gpio, gpio)

/* pa22a_hsmci_mcda1 */
#define PA22A_HSMCI_MCDA1 \
	SAM_PINMUX(a, 22, a, periph)

/* pa22b_tc1_tclk3 */
#define PA22B_TC1_TCLK3 \
	SAM_PINMUX(a, 22, b, periph)

/* pa22x_adc_ad4 */
#define PA22X_ADC_AD4 \
	SAM_PINMUX(a, 22, x, extra)

/* pa23_gpio */
#define PA23_GPIO \
	SAM_PINMUX(a, 23, gpio, gpio)

/* pa23a_hsmci_mcda2 */
#define PA23A_HSMCI_MCDA2 \
	SAM_PINMUX(a, 23, a, periph)

/* pa23b_tc1_tclk4 */
#define PA23B_TC1_TCLK4 \
	SAM_PINMUX(a, 23, b, periph)

/* pa23x_adc_ad5 */
#define PA23X_ADC_AD5 \
	SAM_PINMUX(a, 23, x, extra)

/* pa24_gpio */
#define PA24_GPIO \
	SAM_PINMUX(a, 24, gpio, gpio)

/* pa24a_hsmci_mcda3 */
#define PA24A_HSMCI_MCDA3 \
	SAM_PINMUX(a, 24, a, periph)

/* pa24b_pmc_pck1 */
#define PA24B_PMC_PCK1 \
	SAM_PINMUX(a, 24, b, periph)

/* pa24x_adc_ad6 */
#define PA24X_ADC_AD6 \
	SAM_PINMUX(a, 24, x, extra)

/* pa25_gpio */
#define PA25_GPIO \
	SAM_PINMUX(a, 25, gpio, gpio)

/* pa25a_spi0_miso */
#define PA25A_SPI0_MISO \
	SAM_PINMUX(a, 25, a, periph)

/* pa25b_ebi_a18 */
#define PA25B_EBI_A18 \
	SAM_PINMUX(a, 25, b, periph)

/* pa26_gpio */
#define PA26_GPIO \
	SAM_PINMUX(a, 26, gpio, gpio)

/* pa26a_spi0_mosi */
#define PA26A_SPI0_MOSI \
	SAM_PINMUX(a, 26, a, periph)

/* pa26b_ebi_a19 */
#define PA26B_EBI_A19 \
	SAM_PINMUX(a, 26, b, periph)

/* pa27_gpio */
#define PA27_GPIO \
	SAM_PINMUX(a, 27, gpio, gpio)

/* pa27a_spi0_spck */
#define PA27A_SPI0_SPCK \
	SAM_PINMUX(a, 27, a, periph)

/* pa27b_ebi_a20 */
#define PA27B_EBI_A20 \
	SAM_PINMUX(a, 27, b, periph)

/* pa27x_supc_wkup10 */
#define PA27X_SUPC_WKUP10 \
	SAM_PINMUX(a, 27, x, extra)

/* pa28_gpio */
#define PA28_GPIO \
	SAM_PINMUX(a, 28, gpio, gpio)

/* pa28a_spi0_npcs0 */
#define PA28A_SPI0_NPCS0 \
	SAM_PINMUX(a, 28, a, periph)

/* pa28b_pmc_pck2 */
#define PA28B_PMC_PCK2 \
	SAM_PINMUX(a, 28, b, periph)

/* pa28x_supc_wkup11 */
#define PA28X_SUPC_WKUP11 \
	SAM_PINMUX(a, 28, x, extra)

/* pa29_gpio */
#define PA29_GPIO \
	SAM_PINMUX(a, 29, gpio, gpio)

/* pa29a_spi0_npcs1 */
#define PA29A_SPI0_NPCS1 \
	SAM_PINMUX(a, 29, a, periph)

/* pa29b_ebi_nrd */
#define PA29B_EBI_NRD \
	SAM_PINMUX(a, 29, b, periph)

/* pb00_gpio */
#define PB00_GPIO \
	SAM_PINMUX(b, 0, gpio, gpio)

/* pb00a_emac_etxck_erefck */
#define PB00A_EMAC_ETXCK_EREFCK \
	SAM_PINMUX(b, 0, a, periph)

/* pb00b_tc1_tioa3 */
#define PB00B_TC1_TIOA3 \
	SAM_PINMUX(b, 0, b, periph)

/* pb01_gpio */
#define PB01_GPIO \
	SAM_PINMUX(b, 1, gpio, gpio)

/* pb01a_emac_etxen */
#define PB01A_EMAC_ETXEN \
	SAM_PINMUX(b, 1, a, periph)

/* pb01b_tc1_tiob3 */
#define PB01B_TC1_TIOB3 \
	SAM_PINMUX(b, 1, b, periph)

/* pb02_gpio */
#define PB02_GPIO \
	SAM_PINMUX(b, 2, gpio, gpio)

/* pb02a_emac_etx0 */
#define PB02A_EMAC_ETX0 \
	SAM_PINMUX(b, 2, a, periph)

/* pb02b_tc1_tioa4 */
#define PB02B_TC1_TIOA4 \
	SAM_PINMUX(b, 2, b, periph)

/* pb03_gpio */
#define PB03_GPIO \
	SAM_PINMUX(b, 3, gpio, gpio)

/* pb03a_emac_etx1 */
#define PB03A_EMAC_ETX1 \
	SAM_PINMUX(b, 3, a, periph)

/* pb03b_tc1_tiob4 */
#define PB03B_TC1_TIOB4 \
	SAM_PINMUX(b, 3, b, periph)

/* pb04_gpio */
#define PB04_GPIO \
	SAM_PINMUX(b, 4, gpio, gpio)

/* pb04a_emac_ecrsdv_erxdv */
#define PB04A_EMAC_ECRSDV_ERXDV \
	SAM_PINMUX(b, 4, a, periph)

/* pb04b_tc1_tioa5 */
#define PB04B_TC1_TIOA5 \
	SAM_PINMUX(b, 4, b, periph)

/* pb05_gpio */
#define PB05_GPIO \
	SAM_PINMUX(b, 5, gpio, gpio)

/* pb05a_emac_erx0 */
#define PB05A_EMAC_ERX0 \
	SAM_PINMUX(b, 5, a, periph)

/* pb05b_tc1_tiob5 */
#define PB05B_TC1_TIOB5 \
	SAM_PINMUX(b, 5, b, periph)

/* pb06_gpio */
#define PB06_GPIO \
	SAM_PINMUX(b, 6, gpio, gpio)

/* pb06a_emac_erx1 */
#define PB06A_EMAC_ERX1 \
	SAM_PINMUX(b, 6, a, periph)

/* pb06b_pwm_pwml4 */
#define PB06B_PWM_PWML4 \
	SAM_PINMUX(b, 6, b, periph)

/* pb07_gpio */
#define PB07_GPIO \
	SAM_PINMUX(b, 7, gpio, gpio)

/* pb07a_emac_erxer */
#define PB07A_EMAC_ERXER \
	SAM_PINMUX(b, 7, a, periph)

/* pb07b_pwm_pwml5 */
#define PB07B_PWM_PWML5 \
	SAM_PINMUX(b, 7, b, periph)

/* pb08_gpio */
#define PB08_GPIO \
	SAM_PINMUX(b, 8, gpio, gpio)

/* pb08a_emac_emdc */
#define PB08A_EMAC_EMDC \
	SAM_PINMUX(b, 8, a, periph)

/* pb08b_pwm_pwml6 */
#define PB08B_PWM_PWML6 \
	SAM_PINMUX(b, 8, b, periph)

/* pb09_gpio */
#define PB09_GPIO \
	SAM_PINMUX(b, 9, gpio, gpio)

/* pb09a_emac_emdio */
#define PB09A_EMAC_EMDIO \
	SAM_PINMUX(b, 9, a, periph)

/* pb09b_pwm_pwml7 */
#define PB09B_PWM_PWML7 \
	SAM_PINMUX(b, 9, b, periph)

/* pb10_gpio */
#define PB10_GPIO \
	SAM_PINMUX(b, 10, gpio, gpio)

/* pb10a_uotg_vbof */
#define PB10A_UOTG_VBOF \
	SAM_PINMUX(b, 10, a, periph)

/* pb10b_ebi_a18 */
#define PB10B_EBI_A18 \
	SAM_PINMUX(b, 10, b, periph)

/* pb11_gpio */
#define PB11_GPIO \
	SAM_PINMUX(b, 11, gpio, gpio)

/* pb11a_uotg_id */
#define PB11A_UOTG_ID \
	SAM_PINMUX(b, 11, a, periph)

/* pb11b_ebi_a19 */
#define PB11B_EBI_A19 \
	SAM_PINMUX(b, 11, b, periph)

/* pb12_gpio */
#define PB12_GPIO \
	SAM_PINMUX(b, 12, gpio, gpio)

/* pb12a_twi1_twd */
#define PB12A_TWI1_TWD \
	SAM_PINMUX(b, 12, a, periph)

/* pb12b_pwm_pwmh0 */
#define PB12B_PWM_PWMH0 \
	SAM_PINMUX(b, 12, b, periph)

/* pb12x_adc_ad8 */
#define PB12X_ADC_AD8 \
	SAM_PINMUX(b, 12, x, extra)

/* pb13_gpio */
#define PB13_GPIO \
	SAM_PINMUX(b, 13, gpio, gpio)

/* pb13a_twi1_twck */
#define PB13A_TWI1_TWCK \
	SAM_PINMUX(b, 13, a, periph)

/* pb13b_pwm_pwmh1 */
#define PB13B_PWM_PWMH1 \
	SAM_PINMUX(b, 13, b, periph)

/* pb13x_adc_ad9 */
#define PB13X_ADC_AD9 \
	SAM_PINMUX(b, 13, x, extra)

/* pb14_gpio */
#define PB14_GPIO \
	SAM_PINMUX(b, 14, gpio, gpio)

/* pb14a_can1_tx */
#define PB14A_CAN1_TX \
	SAM_PINMUX(b, 14, a, periph)

/* pb14b_pwm_pwmh2 */
#define PB14B_PWM_PWMH2 \
	SAM_PINMUX(b, 14, b, periph)

/* pb15_gpio */
#define PB15_GPIO \
	SAM_PINMUX(b, 15, gpio, gpio)

/* pb15a_can1_rx */
#define PB15A_CAN1_RX \
	SAM_PINMUX(b, 15, a, periph)

/* pb15b_pwm_pwmh3 */
#define PB15B_PWM_PWMH3 \
	SAM_PINMUX(b, 15, b, periph)

/* pb15x_dacc_dac0 */
#define PB15X_DACC_DAC0 \
	SAM_PINMUX(b, 15, x, extra)

/* pb15x_supc_wkup10 */
#define PB15X_SUPC_WKUP10 \
	SAM_PINMUX(b, 15, x, extra)

/* pb16_gpio */
#define PB16_GPIO \
	SAM_PINMUX(b, 16, gpio, gpio)

/* pb16a_tc1_tclk5 */
#define PB16A_TC1_TCLK5 \
	SAM_PINMUX(b, 16, a, periph)

/* pb16b_pwm_pwml0 */
#define PB16B_PWM_PWML0 \
	SAM_PINMUX(b, 16, b, periph)

/* pb16x_dacc_dac1 */
#define PB16X_DACC_DAC1 \
	SAM_PINMUX(b, 16, x, extra)

/* pb17_gpio */
#define PB17_GPIO \
	SAM_PINMUX(b, 17, gpio, gpio)

/* pb17a_ssc_rf */
#define PB17A_SSC_RF \
	SAM_PINMUX(b, 17, a, periph)

/* pb17b_pwm_pwml1 */
#define PB17B_PWM_PWML1 \
	SAM_PINMUX(b, 17, b, periph)

/* pb17x_adc_ad10 */
#define PB17X_ADC_AD10 \
	SAM_PINMUX(b, 17, x, extra)

/* pb18_gpio */
#define PB18_GPIO \
	SAM_PINMUX(b, 18, gpio, gpio)

/* pb18a_ssc_rd */
#define PB18A_SSC_RD \
	SAM_PINMUX(b, 18, a, periph)

/* pb18b_pwm_pwml2 */
#define PB18B_PWM_PWML2 \
	SAM_PINMUX(b, 18, b, periph)

/* pb18x_adc_ad11 */
#define PB18X_ADC_AD11 \
	SAM_PINMUX(b, 18, x, extra)

/* pb19_gpio */
#define PB19_GPIO \
	SAM_PINMUX(b, 19, gpio, gpio)

/* pb19a_ssc_rk */
#define PB19A_SSC_RK \
	SAM_PINMUX(b, 19, a, periph)

/* pb19b_pwm_pwml3 */
#define PB19B_PWM_PWML3 \
	SAM_PINMUX(b, 19, b, periph)

/* pb19x_adc_ad12 */
#define PB19X_ADC_AD12 \
	SAM_PINMUX(b, 19, x, extra)

/* pb20_gpio */
#define PB20_GPIO \
	SAM_PINMUX(b, 20, gpio, gpio)

/* pb20a_usart2_txd */
#define PB20A_USART2_TXD \
	SAM_PINMUX(b, 20, a, periph)

/* pb20b_spi0_npcs1 */
#define PB20B_SPI0_NPCS1 \
	SAM_PINMUX(b, 20, b, periph)

/* pb20x_adc_ad13 */
#define PB20X_ADC_AD13 \
	SAM_PINMUX(b, 20, x, extra)

/* pb21_gpio */
#define PB21_GPIO \
	SAM_PINMUX(b, 21, gpio, gpio)

/* pb21a_usart2_rxd */
#define PB21A_USART2_RXD \
	SAM_PINMUX(b, 21, a, periph)

/* pb21b_spi0_npcs2 */
#define PB21B_SPI0_NPCS2 \
	SAM_PINMUX(b, 21, b, periph)

/* pb21x_adc_ad14 */
#define PB21X_ADC_AD14 \
	SAM_PINMUX(b, 21, x, extra)

/* pb21x_supc_wkup13 */
#define PB21X_SUPC_WKUP13 \
	SAM_PINMUX(b, 21, x, extra)

/* pb22_gpio */
#define PB22_GPIO \
	SAM_PINMUX(b, 22, gpio, gpio)

/* pb22a_usart2_rts */
#define PB22A_USART2_RTS \
	SAM_PINMUX(b, 22, a, periph)

/* pb22b_pmc_pck0 */
#define PB22B_PMC_PCK0 \
	SAM_PINMUX(b, 22, b, periph)

/* pb23_gpio */
#define PB23_GPIO \
	SAM_PINMUX(b, 23, gpio, gpio)

/* pb23a_usart2_cts */
#define PB23A_USART2_CTS \
	SAM_PINMUX(b, 23, a, periph)

/* pb23b_spi0_npcs3 */
#define PB23B_SPI0_NPCS3 \
	SAM_PINMUX(b, 23, b, periph)

/* pb23x_supc_wkup14 */
#define PB23X_SUPC_WKUP14 \
	SAM_PINMUX(b, 23, x, extra)

/* pb24_gpio */
#define PB24_GPIO \
	SAM_PINMUX(b, 24, gpio, gpio)

/* pb24a_usart2_sck */
#define PB24A_USART2_SCK \
	SAM_PINMUX(b, 24, a, periph)

/* pb24b_ebi_ncs2 */
#define PB24B_EBI_NCS2 \
	SAM_PINMUX(b, 24, b, periph)

/* pb25_gpio */
#define PB25_GPIO \
	SAM_PINMUX(b, 25, gpio, gpio)

/* pb25a_usart0_rts */
#define PB25A_USART0_RTS \
	SAM_PINMUX(b, 25, a, periph)

/* pb25b_tc0_tioa0 */
#define PB25B_TC0_TIOA0 \
	SAM_PINMUX(b, 25, b, periph)

/* pb26_gpio */
#define PB26_GPIO \
	SAM_PINMUX(b, 26, gpio, gpio)

/* pb26a_usart0_cts */
#define PB26A_USART0_CTS \
	SAM_PINMUX(b, 26, a, periph)

/* pb26b_tc0_tclk0 */
#define PB26B_TC0_TCLK0 \
	SAM_PINMUX(b, 26, b, periph)

/* pb26x_supc_wkup15 */
#define PB26X_SUPC_WKUP15 \
	SAM_PINMUX(b, 26, x, extra)

/* pb27_gpio */
#define PB27_GPIO \
	SAM_PINMUX(b, 27, gpio, gpio)

/* pb27a_ebi_ncs3 */
#define PB27A_EBI_NCS3 \
	SAM_PINMUX(b, 27, a, periph)

/* pb27b_tc0_tiob0 */
#define PB27B_TC0_TIOB0 \
	SAM_PINMUX(b, 27, b, periph)

/* pb28_gpio */
#define PB28_GPIO \
	SAM_PINMUX(b, 28, gpio, gpio)

/* pb29_gpio */
#define PB29_GPIO \
	SAM_PINMUX(b, 29, gpio, gpio)

/* pb30_gpio */
#define PB30_GPIO \
	SAM_PINMUX(b, 30, gpio, gpio)

/* pb31_gpio */
#define PB31_GPIO \
	SAM_PINMUX(b, 31, gpio, gpio)

/* pc00_gpio */
#define PC00_GPIO \
	SAM_PINMUX(c, 0, gpio, gpio)

/* pc00x_flash_erase */
#define PC00X_FLASH_ERASE \
	SAM_PINMUX(c, 0, x, extra)

/* pc01_gpio */
#define PC01_GPIO \
	SAM_PINMUX(c, 1, gpio, gpio)

/* pc02_gpio */
#define PC02_GPIO \
	SAM_PINMUX(c, 2, gpio, gpio)

/* pc02a_ebi_d0 */
#define PC02A_EBI_D0 \
	SAM_PINMUX(c, 2, a, periph)

/* pc02b_pwm_pwml0 */
#define PC02B_PWM_PWML0 \
	SAM_PINMUX(c, 2, b, periph)

/* pc03_gpio */
#define PC03_GPIO \
	SAM_PINMUX(c, 3, gpio, gpio)

/* pc03a_ebi_d1 */
#define PC03A_EBI_D1 \
	SAM_PINMUX(c, 3, a, periph)

/* pc03b_pwm_pwmh0 */
#define PC03B_PWM_PWMH0 \
	SAM_PINMUX(c, 3, b, periph)

/* pc04_gpio */
#define PC04_GPIO \
	SAM_PINMUX(c, 4, gpio, gpio)

/* pc04a_ebi_d2 */
#define PC04A_EBI_D2 \
	SAM_PINMUX(c, 4, a, periph)

/* pc04b_pwm_pwml1 */
#define PC04B_PWM_PWML1 \
	SAM_PINMUX(c, 4, b, periph)

/* pc05_gpio */
#define PC05_GPIO \
	SAM_PINMUX(c, 5, gpio, gpio)

/* pc05a_ebi_d3 */
#define PC05A_EBI_D3 \
	SAM_PINMUX(c, 5, a, periph)

/* pc05b_pwm_pwmh1 */
#define PC05B_PWM_PWMH1 \
	SAM_PINMUX(c, 5, b, periph)

/* pc06_gpio */
#define PC06_GPIO \
	SAM_PINMUX(c, 6, gpio, gpio)

/* pc06a_ebi_d4 */
#define PC06A_EBI_D4 \
	SAM_PINMUX(c, 6, a, periph)

/* pc06b_pwm_pwml2 */
#define PC06B_PWM_PWML2 \
	SAM_PINMUX(c, 6, b, periph)

/* pc07_gpio */
#define PC07_GPIO \
	SAM_PINMUX(c, 7, gpio, gpio)

/* pc07a_ebi_d5 */
#define PC07A_EBI_D5 \
	SAM_PINMUX(c, 7, a, periph)

/* pc07b_pwm_pwmh2 */
#define PC07B_PWM_PWMH2 \
	SAM_PINMUX(c, 7, b, periph)

/* pc08_gpio */
#define PC08_GPIO \
	SAM_PINMUX(c, 8, gpio, gpio)

/* pc08a_ebi_d6 */
#define PC08A_EBI_D6 \
	SAM_PINMUX(c, 8, a, periph)

/* pc08b_pwm_pwml3 */
#define PC08B_PWM_PWML3 \
	SAM_PINMUX(c, 8, b, periph)

/* pc09_gpio */
#define PC09_GPIO \
	SAM_PINMUX(c, 9, gpio, gpio)

/* pc09a_ebi_d7 */
#define PC09A_EBI_D7 \
	SAM_PINMUX(c, 9, a, periph)

/* pc09b_pwm_pwmh3 */
#define PC09B_PWM_PWMH3 \
	SAM_PINMUX(c, 9, b, periph)

/* pc10_gpio */
#define PC10_GPIO \
	SAM_PINMUX(c, 10, gpio, gpio)

/* pc10a_ebi_d8 */
#define PC10A_EBI_D8 \
	SAM_PINMUX(c, 10, a, periph)

/* pc10b_emac_ecrs */
#define PC10B_EMAC_ECRS \
	SAM_PINMUX(c, 10, b, periph)

/* pc11_gpio */
#define PC11_GPIO \
	SAM_PINMUX(c, 11, gpio, gpio)

/* pc11a_ebi_d9 */
#define PC11A_EBI_D9 \
	SAM_PINMUX(c, 11, a, periph)

/* pc11b_emac_erx2 */
#define PC11B_EMAC_ERX2 \
	SAM_PINMUX(c, 11, b, periph)

/* pc12_gpio */
#define PC12_GPIO \
	SAM_PINMUX(c, 12, gpio, gpio)

/* pc12a_ebi_d10 */
#define PC12A_EBI_D10 \
	SAM_PINMUX(c, 12, a, periph)

/* pc12b_emac_erx3 */
#define PC12B_EMAC_ERX3 \
	SAM_PINMUX(c, 12, b, periph)

/* pc13_gpio */
#define PC13_GPIO \
	SAM_PINMUX(c, 13, gpio, gpio)

/* pc13a_ebi_d11 */
#define PC13A_EBI_D11 \
	SAM_PINMUX(c, 13, a, periph)

/* pc13b_emac_ecol */
#define PC13B_EMAC_ECOL \
	SAM_PINMUX(c, 13, b, periph)

/* pc14_gpio */
#define PC14_GPIO \
	SAM_PINMUX(c, 14, gpio, gpio)

/* pc14a_ebi_d12 */
#define PC14A_EBI_D12 \
	SAM_PINMUX(c, 14, a, periph)

/* pc14b_emac_erxck */
#define PC14B_EMAC_ERXCK \
	SAM_PINMUX(c, 14, b, periph)

/* pc15_gpio */
#define PC15_GPIO \
	SAM_PINMUX(c, 15, gpio, gpio)

/* pc15a_ebi_d13 */
#define PC15A_EBI_D13 \
	SAM_PINMUX(c, 15, a, periph)

/* pc15b_emac_etx2 */
#define PC15B_EMAC_ETX2 \
	SAM_PINMUX(c, 15, b, periph)

/* pc16_gpio */
#define PC16_GPIO \
	SAM_PINMUX(c, 16, gpio, gpio)

/* pc16a_ebi_d14 */
#define PC16A_EBI_D14 \
	SAM_PINMUX(c, 16, a, periph)

/* pc16b_emac_etx3 */
#define PC16B_EMAC_ETX3 \
	SAM_PINMUX(c, 16, b, periph)

/* pc17_gpio */
#define PC17_GPIO \
	SAM_PINMUX(c, 17, gpio, gpio)

/* pc17a_ebi_d15 */
#define PC17A_EBI_D15 \
	SAM_PINMUX(c, 17, a, periph)

/* pc17b_emac_etxer */
#define PC17B_EMAC_ETXER \
	SAM_PINMUX(c, 17, b, periph)

/* pc18_gpio */
#define PC18_GPIO \
	SAM_PINMUX(c, 18, gpio, gpio)

/* pc18a_ebi_nwr0_nwe */
#define PC18A_EBI_NWR0_NWE \
	SAM_PINMUX(c, 18, a, periph)

/* pc18b_pwm_pwmh6 */
#define PC18B_PWM_PWMH6 \
	SAM_PINMUX(c, 18, b, periph)

/* pc19_gpio */
#define PC19_GPIO \
	SAM_PINMUX(c, 19, gpio, gpio)

/* pc19a_ebi_nandoe */
#define PC19A_EBI_NANDOE \
	SAM_PINMUX(c, 19, a, periph)

/* pc19b_pwm_pwmh5 */
#define PC19B_PWM_PWMH5 \
	SAM_PINMUX(c, 19, b, periph)

/* pc20_gpio */
#define PC20_GPIO \
	SAM_PINMUX(c, 20, gpio, gpio)

/* pc20a_ebi_nandwe */
#define PC20A_EBI_NANDWE \
	SAM_PINMUX(c, 20, a, periph)

/* pc20b_pwm_pwmh4 */
#define PC20B_PWM_PWMH4 \
	SAM_PINMUX(c, 20, b, periph)

/* pc21_gpio */
#define PC21_GPIO \
	SAM_PINMUX(c, 21, gpio, gpio)

/* pc21a_ebi_a0_nbs0 */
#define PC21A_EBI_A0_NBS0 \
	SAM_PINMUX(c, 21, a, periph)

/* pc21b_pwm_pwml4 */
#define PC21B_PWM_PWML4 \
	SAM_PINMUX(c, 21, b, periph)

/* pc22_gpio */
#define PC22_GPIO \
	SAM_PINMUX(c, 22, gpio, gpio)

/* pc22a_ebi_a1 */
#define PC22A_EBI_A1 \
	SAM_PINMUX(c, 22, a, periph)

/* pc22b_pwm_pwml5 */
#define PC22B_PWM_PWML5 \
	SAM_PINMUX(c, 22, b, periph)

/* pc23_gpio */
#define PC23_GPIO \
	SAM_PINMUX(c, 23, gpio, gpio)

/* pc23a_ebi_a2 */
#define PC23A_EBI_A2 \
	SAM_PINMUX(c, 23, a, periph)

/* pc23b_pwm_pwml6 */
#define PC23B_PWM_PWML6 \
	SAM_PINMUX(c, 23, b, periph)

/* pc24_gpio */
#define PC24_GPIO \
	SAM_PINMUX(c, 24, gpio, gpio)

/* pc24a_ebi_a3 */
#define PC24A_EBI_A3 \
	SAM_PINMUX(c, 24, a, periph)

/* pc24b_pwm_pwml7 */
#define PC24B_PWM_PWML7 \
	SAM_PINMUX(c, 24, b, periph)

/* pc25_gpio */
#define PC25_GPIO \
	SAM_PINMUX(c, 25, gpio, gpio)

/* pc25a_ebi_a4 */
#define PC25A_EBI_A4 \
	SAM_PINMUX(c, 25, a, periph)

/* pc25b_tc2_tioa6 */
#define PC25B_TC2_TIOA6 \
	SAM_PINMUX(c, 25, b, periph)

/* pc26_gpio */
#define PC26_GPIO \
	SAM_PINMUX(c, 26, gpio, gpio)

/* pc26a_ebi_a5 */
#define PC26A_EBI_A5 \
	SAM_PINMUX(c, 26, a, periph)

/* pc26b_tc2_tiob6 */
#define PC26B_TC2_TIOB6 \
	SAM_PINMUX(c, 26, b, periph)

/* pc27_gpio */
#define PC27_GPIO \
	SAM_PINMUX(c, 27, gpio, gpio)

/* pc27a_ebi_a6 */
#define PC27A_EBI_A6 \
	SAM_PINMUX(c, 27, a, periph)

/* pc27b_tc2_tclk6 */
#define PC27B_TC2_TCLK6 \
	SAM_PINMUX(c, 27, b, periph)

/* pc28_gpio */
#define PC28_GPIO \
	SAM_PINMUX(c, 28, gpio, gpio)

/* pc28a_ebi_a7 */
#define PC28A_EBI_A7 \
	SAM_PINMUX(c, 28, a, periph)

/* pc28b_tc2_tioa7 */
#define PC28B_TC2_TIOA7 \
	SAM_PINMUX(c, 28, b, periph)

/* pc29_gpio */
#define PC29_GPIO \
	SAM_PINMUX(c, 29, gpio, gpio)

/* pc29a_ebi_a8 */
#define PC29A_EBI_A8 \
	SAM_PINMUX(c, 29, a, periph)

/* pc29b_tc2_tiob7 */
#define PC29B_TC2_TIOB7 \
	SAM_PINMUX(c, 29, b, periph)

/* pc30_gpio */
#define PC30_GPIO \
	SAM_PINMUX(c, 30, gpio, gpio)

/* pc30a_ebi_a9 */
#define PC30A_EBI_A9 \
	SAM_PINMUX(c, 30, a, periph)

/* pc30b_tc2_tclk7 */
#define PC30B_TC2_TCLK7 \
	SAM_PINMUX(c, 30, b, periph)

/* pd00_gpio */
#define PD00_GPIO \
	SAM_PINMUX(d, 0, gpio, gpio)

/* pd00a_ebi_a10 */
#define PD00A_EBI_A10 \
	SAM_PINMUX(d, 0, a, periph)

/* pd00b_hsmci_mcda4 */
#define PD00B_HSMCI_MCDA4 \
	SAM_PINMUX(d, 0, b, periph)

/* pd01_gpio */
#define PD01_GPIO \
	SAM_PINMUX(d, 1, gpio, gpio)

/* pd01a_ebi_a11 */
#define PD01A_EBI_A11 \
	SAM_PINMUX(d, 1, a, periph)

/* pd01b_hsmci_mcda5 */
#define PD01B_HSMCI_MCDA5 \
	SAM_PINMUX(d, 1, b, periph)

/* pd02_gpio */
#define PD02_GPIO \
	SAM_PINMUX(d, 2, gpio, gpio)

/* pd02a_ebi_a12 */
#define PD02A_EBI_A12 \
	SAM_PINMUX(d, 2, a, periph)

/* pd02b_hsmci_mcda6 */
#define PD02B_HSMCI_MCDA6 \
	SAM_PINMUX(d, 2, b, periph)

/* pd03_gpio */
#define PD03_GPIO \
	SAM_PINMUX(d, 3, gpio, gpio)

/* pd03a_ebi_a13 */
#define PD03A_EBI_A13 \
	SAM_PINMUX(d, 3, a, periph)

/* pd03b_hsmci_mcda7 */
#define PD03B_HSMCI_MCDA7 \
	SAM_PINMUX(d, 3, b, periph)

/* pd04_gpio */
#define PD04_GPIO \
	SAM_PINMUX(d, 4, gpio, gpio)

/* pd04a_ebi_a14 */
#define PD04A_EBI_A14 \
	SAM_PINMUX(d, 4, a, periph)

/* pd04b_usart3_txd */
#define PD04B_USART3_TXD \
	SAM_PINMUX(d, 4, b, periph)

/* pd05_gpio */
#define PD05_GPIO \
	SAM_PINMUX(d, 5, gpio, gpio)

/* pd05a_ebi_a15 */
#define PD05A_EBI_A15 \
	SAM_PINMUX(d, 5, a, periph)

/* pd05b_usart3_rxd */
#define PD05B_USART3_RXD \
	SAM_PINMUX(d, 5, b, periph)

/* pd06_gpio */
#define PD06_GPIO \
	SAM_PINMUX(d, 6, gpio, gpio)

/* pd06a_ebi_a16_ba0 */
#define PD06A_EBI_A16_BA0 \
	SAM_PINMUX(d, 6, a, periph)

/* pd06b_pwm_pwmfi2 */
#define PD06B_PWM_PWMFI2 \
	SAM_PINMUX(d, 6, b, periph)

/* pd07_gpio */
#define PD07_GPIO \
	SAM_PINMUX(d, 7, gpio, gpio)

/* pd07a_ebi_a17_ba1 */
#define PD07A_EBI_A17_BA1 \
	SAM_PINMUX(d, 7, a, periph)

/* pd07b_tc2_tioa8 */
#define PD07B_TC2_TIOA8 \
	SAM_PINMUX(d, 7, b, periph)

/* pd08_gpio */
#define PD08_GPIO \
	SAM_PINMUX(d, 8, gpio, gpio)

/* pd08a_ebi_a21_nandale */
#define PD08A_EBI_A21_NANDALE \
	SAM_PINMUX(d, 8, a, periph)

/* pd08b_tc2_tiob8 */
#define PD08B_TC2_TIOB8 \
	SAM_PINMUX(d, 8, b, periph)

/* pd09_gpio */
#define PD09_GPIO \
	SAM_PINMUX(d, 9, gpio, gpio)

/* pd09a_ebi_a22_nandcle */
#define PD09A_EBI_A22_NANDCLE \
	SAM_PINMUX(d, 9, a, periph)

/* pd09b_tc2_tclk9 */
#define PD09B_TC2_TCLK9 \
	SAM_PINMUX(d, 9, b, periph)

/* pd10_gpio */
#define PD10_GPIO \
	SAM_PINMUX(d, 10, gpio, gpio)

/* pd10a_ebi_nwr1_nbs1 */
#define PD10A_EBI_NWR1_NBS1 \
	SAM_PINMUX(d, 10, a, periph)

/* pe09_gpio */
#define PE09_GPIO \
	SAM_PINMUX(e, 9, gpio, gpio)

/* pe09a_tc1_tioa3 */
#define PE09A_TC1_TIOA3 \
	SAM_PINMUX(e, 9, a, periph)

/* pe10_gpio */
#define PE10_GPIO \
	SAM_PINMUX(e, 10, gpio, gpio)

/* pe10a_tc1_tiob3 */
#define PE10A_TC1_TIOB3 \
	SAM_PINMUX(e, 10, a, periph)

/* pe11_gpio */
#define PE11_GPIO \
	SAM_PINMUX(e, 11, gpio, gpio)

/* pe11a_tc1_tioa4 */
#define PE11A_TC1_TIOA4 \
	SAM_PINMUX(e, 11, a, periph)

/* pe12_gpio */
#define PE12_GPIO \
	SAM_PINMUX(e, 12, gpio, gpio)

/* pe12a_tc1_tiob4 */
#define PE12A_TC1_TIOB4 \
	SAM_PINMUX(e, 12, a, periph)

/* pe13_gpio */
#define PE13_GPIO \
	SAM_PINMUX(e, 13, gpio, gpio)

/* pe13a_tc1_tioa5 */
#define PE13A_TC1_TIOA5 \
	SAM_PINMUX(e, 13, a, periph)

/* pe14_gpio */
#define PE14_GPIO \
	SAM_PINMUX(e, 14, gpio, gpio)

/* pe14a_tc1_tiob5 */
#define PE14A_TC1_TIOB5 \
	SAM_PINMUX(e, 14, a, periph)

/* pe15_gpio */
#define PE15_GPIO \
	SAM_PINMUX(e, 15, gpio, gpio)

/* pe15a_pwm_pwmh0 */
#define PE15A_PWM_PWMH0 \
	SAM_PINMUX(e, 15, a, periph)

/* pe16_gpio */
#define PE16_GPIO \
	SAM_PINMUX(e, 16, gpio, gpio)

/* pe16a_pwm_pwmh1 */
#define PE16A_PWM_PWMH1 \
	SAM_PINMUX(e, 16, a, periph)

/* pe16b_usart3_sck */
#define PE16B_USART3_SCK \
	SAM_PINMUX(e, 16, b, periph)

/* pe17_gpio */
#define PE17_GPIO \
	SAM_PINMUX(e, 17, gpio, gpio)

/* pe17a_pwm_pwml2 */
#define PE17A_PWM_PWML2 \
	SAM_PINMUX(e, 17, a, periph)

/* pe18_gpio */
#define PE18_GPIO \
	SAM_PINMUX(e, 18, gpio, gpio)

/* pe18a_pwm_pwml0 */
#define PE18A_PWM_PWML0 \
	SAM_PINMUX(e, 18, a, periph)

/* pe18b_ebi_ncs6 */
#define PE18B_EBI_NCS6 \
	SAM_PINMUX(e, 18, b, periph)

/* pe19_gpio */
#define PE19_GPIO \
	SAM_PINMUX(e, 19, gpio, gpio)

/* pe19a_pwm_pwml4 */
#define PE19A_PWM_PWML4 \
	SAM_PINMUX(e, 19, a, periph)

/* pe20_gpio */
#define PE20_GPIO \
	SAM_PINMUX(e, 20, gpio, gpio)

/* pe20a_pwm_pwmh4 */
#define PE20A_PWM_PWMH4 \
	SAM_PINMUX(e, 20, a, periph)

/* pe20b_hsmci_mccdb */
#define PE20B_HSMCI_MCCDB \
	SAM_PINMUX(e, 20, b, periph)

/* pe21_gpio */
#define PE21_GPIO \
	SAM_PINMUX(e, 21, gpio, gpio)

/* pe21a_pwm_pwml5 */
#define PE21A_PWM_PWML5 \
	SAM_PINMUX(e, 21, a, periph)

/* pe22_gpio */
#define PE22_GPIO \
	SAM_PINMUX(e, 22, gpio, gpio)

/* pe22a_pwm_pwmh5 */
#define PE22A_PWM_PWMH5 \
	SAM_PINMUX(e, 22, a, periph)

/* pe22b_hsmci_mcdb0 */
#define PE22B_HSMCI_MCDB0 \
	SAM_PINMUX(e, 22, b, periph)

/* pe23_gpio */
#define PE23_GPIO \
	SAM_PINMUX(e, 23, gpio, gpio)

/* pe23a_pwm_pwml6 */
#define PE23A_PWM_PWML6 \
	SAM_PINMUX(e, 23, a, periph)

/* pe24_gpio */
#define PE24_GPIO \
	SAM_PINMUX(e, 24, gpio, gpio)

/* pe24a_pwm_pwmh6 */
#define PE24A_PWM_PWMH6 \
	SAM_PINMUX(e, 24, a, periph)

/* pe24b_hsmci_mcdb1 */
#define PE24B_HSMCI_MCDB1 \
	SAM_PINMUX(e, 24, b, periph)

/* pe25_gpio */
#define PE25_GPIO \
	SAM_PINMUX(e, 25, gpio, gpio)

/* pe25a_pwm_pwml7 */
#define PE25A_PWM_PWML7 \
	SAM_PINMUX(e, 25, a, periph)

/* pe26_gpio */
#define PE26_GPIO \
	SAM_PINMUX(e, 26, gpio, gpio)

/* pe26a_pwm_pwmh7 */
#define PE26A_PWM_PWMH7 \
	SAM_PINMUX(e, 26, a, periph)

/* pe26b_hsmci_mcdb2 */
#define PE26B_HSMCI_MCDB2 \
	SAM_PINMUX(e, 26, b, periph)
