/*
 * Autogenerated file
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <dt-bindings/pinctrl/atmel_sam_pinctrl.h>

/* pa00_gpio */
#define PA00_GPIO \
	SAM_PINMUX(a, 0, gpio, gpio)

/* pa00a_eic_extint0 */
#define PA00A_EIC_EXTINT0 \
	SAM_PINMUX(a, 0, a, periph)

/* pa00d_sercom1_pad0 */
#define PA00D_SERCOM1_PAD0 \
	SAM_PINMUX(a, 0, d, periph)

/* pa00e_tcc2_wo0 */
#define PA00E_TCC2_WO0 \
	SAM_PINMUX(a, 0, e, periph)

/* pa00h_ac_cmp2 */
#define PA00H_AC_CMP2 \
	SAM_PINMUX(a, 0, h, periph)

/* pa01_gpio */
#define PA01_GPIO \
	SAM_PINMUX(a, 1, gpio, gpio)

/* pa01a_eic_extint1 */
#define PA01A_EIC_EXTINT1 \
	SAM_PINMUX(a, 1, a, periph)

/* pa01d_sercom1_pad1 */
#define PA01D_SERCOM1_PAD1 \
	SAM_PINMUX(a, 1, d, periph)

/* pa01e_tcc2_wo1 */
#define PA01E_TCC2_WO1 \
	SAM_PINMUX(a, 1, e, periph)

/* pa01h_ac_cmp3 */
#define PA01H_AC_CMP3 \
	SAM_PINMUX(a, 1, h, periph)

/* pa02_gpio */
#define PA02_GPIO \
	SAM_PINMUX(a, 2, gpio, gpio)

/* pa02a_eic_extint2 */
#define PA02A_EIC_EXTINT2 \
	SAM_PINMUX(a, 2, a, periph)

/* pa02b_adc0_ain0 */
#define PA02B_ADC0_AIN0 \
	SAM_PINMUX(a, 2, b, periph)

/* pa02b_ac_ain4 */
#define PA02B_AC_AIN4 \
	SAM_PINMUX(a, 2, b, periph)

/* pa02b_ptc_y0 */
#define PA02B_PTC_Y0 \
	SAM_PINMUX(a, 2, b, periph)

/* pa03_gpio */
#define PA03_GPIO \
	SAM_PINMUX(a, 3, gpio, gpio)

/* pa03a_eic_extint3 */
#define PA03A_EIC_EXTINT3 \
	SAM_PINMUX(a, 3, a, periph)

/* pa03b_adc_dac_vrefa */
#define PA03B_ADC_DAC_VREFA \
	SAM_PINMUX(a, 3, b, periph)

/* pa03b_adc0_ain1 */
#define PA03B_ADC0_AIN1 \
	SAM_PINMUX(a, 3, b, periph)

/* pa03b_ac_ain5 */
#define PA03B_AC_AIN5 \
	SAM_PINMUX(a, 3, b, periph)

/* pa03b_ptc_y1 */
#define PA03B_PTC_Y1 \
	SAM_PINMUX(a, 3, b, periph)

/* pa04_gpio */
#define PA04_GPIO \
	SAM_PINMUX(a, 4, gpio, gpio)

/* pa04a_eic_extint4 */
#define PA04A_EIC_EXTINT4 \
	SAM_PINMUX(a, 4, a, periph)

/* pa04b_sdadc_vrefb */
#define PA04B_SDADC_VREFB \
	SAM_PINMUX(a, 4, b, periph)

/* pa04b_adc0_ain4 */
#define PA04B_ADC0_AIN4 \
	SAM_PINMUX(a, 4, b, periph)

/* pa04b_ac_ain0 */
#define PA04B_AC_AIN0 \
	SAM_PINMUX(a, 4, b, periph)

/* pa04b_ptc_y2 */
#define PA04B_PTC_Y2 \
	SAM_PINMUX(a, 4, b, periph)

/* pa04d_sercom0_pad0 */
#define PA04D_SERCOM0_PAD0 \
	SAM_PINMUX(a, 4, d, periph)

/* pa04e_tcc0_wo0 */
#define PA04E_TCC0_WO0 \
	SAM_PINMUX(a, 4, e, periph)

/* pa04i_ccl0_in0 */
#define PA04I_CCL0_IN0 \
	SAM_PINMUX(a, 4, i, periph)

/* pa05_gpio */
#define PA05_GPIO \
	SAM_PINMUX(a, 5, gpio, gpio)

/* pa05a_eic_extint5 */
#define PA05A_EIC_EXTINT5 \
	SAM_PINMUX(a, 5, a, periph)

/* pa05b_adc0_ain5 */
#define PA05B_ADC0_AIN5 \
	SAM_PINMUX(a, 5, b, periph)

/* pa05b_ac_ain1 */
#define PA05B_AC_AIN1 \
	SAM_PINMUX(a, 5, b, periph)

/* pa05b_ptc_y3 */
#define PA05B_PTC_Y3 \
	SAM_PINMUX(a, 5, b, periph)

/* pa05d_sercom0_pad1 */
#define PA05D_SERCOM0_PAD1 \
	SAM_PINMUX(a, 5, d, periph)

/* pa05e_tcc0_wo1 */
#define PA05E_TCC0_WO1 \
	SAM_PINMUX(a, 5, e, periph)

/* pa05i_ccl0_in1 */
#define PA05I_CCL0_IN1 \
	SAM_PINMUX(a, 5, i, periph)

/* pa06_gpio */
#define PA06_GPIO \
	SAM_PINMUX(a, 6, gpio, gpio)

/* pa06a_eic_extint6 */
#define PA06A_EIC_EXTINT6 \
	SAM_PINMUX(a, 6, a, periph)

/* pa06b_adc0_ain6 */
#define PA06B_ADC0_AIN6 \
	SAM_PINMUX(a, 6, b, periph)

/* pa06b_ac_ain2 */
#define PA06B_AC_AIN2 \
	SAM_PINMUX(a, 6, b, periph)

/* pa06b_ptc_y4 */
#define PA06B_PTC_Y4 \
	SAM_PINMUX(a, 6, b, periph)

/* pa06d_sercom0_pad2 */
#define PA06D_SERCOM0_PAD2 \
	SAM_PINMUX(a, 6, d, periph)

/* pa06e_tcc1_wo0 */
#define PA06E_TCC1_WO0 \
	SAM_PINMUX(a, 6, e, periph)

/* pa06i_ccl0_in2 */
#define PA06I_CCL0_IN2 \
	SAM_PINMUX(a, 6, i, periph)

/* pa07_gpio */
#define PA07_GPIO \
	SAM_PINMUX(a, 7, gpio, gpio)

/* pa07a_eic_extint7 */
#define PA07A_EIC_EXTINT7 \
	SAM_PINMUX(a, 7, a, periph)

/* pa07b_adc0_ain7 */
#define PA07B_ADC0_AIN7 \
	SAM_PINMUX(a, 7, b, periph)

/* pa07b_ac_ain3 */
#define PA07B_AC_AIN3 \
	SAM_PINMUX(a, 7, b, periph)

/* pa07b_ptc_y5 */
#define PA07B_PTC_Y5 \
	SAM_PINMUX(a, 7, b, periph)

/* pa07d_sercom0_pad3 */
#define PA07D_SERCOM0_PAD3 \
	SAM_PINMUX(a, 7, d, periph)

/* pa07e_tcc1_wo1 */
#define PA07E_TCC1_WO1 \
	SAM_PINMUX(a, 7, e, periph)

/* pa07i_ccl0_out0 */
#define PA07I_CCL0_OUT0 \
	SAM_PINMUX(a, 7, i, periph)

/* pa08_gpio */
#define PA08_GPIO \
	SAM_PINMUX(a, 8, gpio, gpio)

/* pa08a_eic_nmi */
#define PA08A_EIC_NMI \
	SAM_PINMUX(a, 8, a, periph)

/* pa08b_adc0_ain8 */
#define PA08B_ADC0_AIN8 \
	SAM_PINMUX(a, 8, b, periph)

/* pa08b_ptc_x0 */
#define PA08B_PTC_X0 \
	SAM_PINMUX(a, 8, b, periph)

/* pa08b_ptc_y16 */
#define PA08B_PTC_Y16 \
	SAM_PINMUX(a, 8, b, periph)

/* pa08c_sercom0_pad0 */
#define PA08C_SERCOM0_PAD0 \
	SAM_PINMUX(a, 8, c, periph)

/* pa08d_sercom2_pad0 */
#define PA08D_SERCOM2_PAD0 \
	SAM_PINMUX(a, 8, d, periph)

/* pa08e_tcc0_wo0 */
#define PA08E_TCC0_WO0 \
	SAM_PINMUX(a, 8, e, periph)

/* pa08f_tcc1_wo2 */
#define PA08F_TCC1_WO2 \
	SAM_PINMUX(a, 8, f, periph)

/* pa08i_ccl1_in3 */
#define PA08I_CCL1_IN3 \
	SAM_PINMUX(a, 8, i, periph)

/* pa09_gpio */
#define PA09_GPIO \
	SAM_PINMUX(a, 9, gpio, gpio)

/* pa09a_eic_extint9 */
#define PA09A_EIC_EXTINT9 \
	SAM_PINMUX(a, 9, a, periph)

/* pa09b_adc0_ain9 */
#define PA09B_ADC0_AIN9 \
	SAM_PINMUX(a, 9, b, periph)

/* pa09b_ptc_x1 */
#define PA09B_PTC_X1 \
	SAM_PINMUX(a, 9, b, periph)

/* pa09b_ptc_y17 */
#define PA09B_PTC_Y17 \
	SAM_PINMUX(a, 9, b, periph)

/* pa09c_sercom0_pad1 */
#define PA09C_SERCOM0_PAD1 \
	SAM_PINMUX(a, 9, c, periph)

/* pa09d_sercom2_pad1 */
#define PA09D_SERCOM2_PAD1 \
	SAM_PINMUX(a, 9, d, periph)

/* pa09e_tcc0_wo1 */
#define PA09E_TCC0_WO1 \
	SAM_PINMUX(a, 9, e, periph)

/* pa09f_tcc1_wo3 */
#define PA09F_TCC1_WO3 \
	SAM_PINMUX(a, 9, f, periph)

/* pa09i_ccl1_in4 */
#define PA09I_CCL1_IN4 \
	SAM_PINMUX(a, 9, i, periph)

/* pa10_gpio */
#define PA10_GPIO \
	SAM_PINMUX(a, 10, gpio, gpio)

/* pa10a_eic_extint10 */
#define PA10A_EIC_EXTINT10 \
	SAM_PINMUX(a, 10, a, periph)

/* pa10b_adc0_ain10 */
#define PA10B_ADC0_AIN10 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10b_ptc_x2 */
#define PA10B_PTC_X2 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10b_ptc_y18 */
#define PA10B_PTC_Y18 \
	SAM_PINMUX(a, 10, b, periph)

/* pa10c_sercom0_pad2 */
#define PA10C_SERCOM0_PAD2 \
	SAM_PINMUX(a, 10, c, periph)

/* pa10d_sercom2_pad2 */
#define PA10D_SERCOM2_PAD2 \
	SAM_PINMUX(a, 10, d, periph)

/* pa10e_tcc1_wo0 */
#define PA10E_TCC1_WO0 \
	SAM_PINMUX(a, 10, e, periph)

/* pa10f_tcc0_wo2 */
#define PA10F_TCC0_WO2 \
	SAM_PINMUX(a, 10, f, periph)

/* pa10h_gclk_io4 */
#define PA10H_GCLK_IO4 \
	SAM_PINMUX(a, 10, h, periph)

/* pa10i_ccl1_in5 */
#define PA10I_CCL1_IN5 \
	SAM_PINMUX(a, 10, i, periph)

/* pa11_gpio */
#define PA11_GPIO \
	SAM_PINMUX(a, 11, gpio, gpio)

/* pa11a_eic_extint11 */
#define PA11A_EIC_EXTINT11 \
	SAM_PINMUX(a, 11, a, periph)

/* pa11b_adc0_ain11 */
#define PA11B_ADC0_AIN11 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11b_ptc_x3 */
#define PA11B_PTC_X3 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11b_ptc_y19 */
#define PA11B_PTC_Y19 \
	SAM_PINMUX(a, 11, b, periph)

/* pa11c_sercom0_pad3 */
#define PA11C_SERCOM0_PAD3 \
	SAM_PINMUX(a, 11, c, periph)

/* pa11d_sercom2_pad3 */
#define PA11D_SERCOM2_PAD3 \
	SAM_PINMUX(a, 11, d, periph)

/* pa11e_tcc1_wo1 */
#define PA11E_TCC1_WO1 \
	SAM_PINMUX(a, 11, e, periph)

/* pa11f_tcc0_wo3 */
#define PA11F_TCC0_WO3 \
	SAM_PINMUX(a, 11, f, periph)

/* pa11h_gclk_io5 */
#define PA11H_GCLK_IO5 \
	SAM_PINMUX(a, 11, h, periph)

/* pa11i_ccl1_out1 */
#define PA11I_CCL1_OUT1 \
	SAM_PINMUX(a, 11, i, periph)

/* pa14_gpio */
#define PA14_GPIO \
	SAM_PINMUX(a, 14, gpio, gpio)

/* pa14a_eic_extint14 */
#define PA14A_EIC_EXTINT14 \
	SAM_PINMUX(a, 14, a, periph)

/* pa14c_sercom2_pad2 */
#define PA14C_SERCOM2_PAD2 \
	SAM_PINMUX(a, 14, c, periph)

/* pa14d_sercom4_pad2 */
#define PA14D_SERCOM4_PAD2 \
	SAM_PINMUX(a, 14, d, periph)

/* pa14e_tc4_wo0 */
#define PA14E_TC4_WO0 \
	SAM_PINMUX(a, 14, e, periph)

/* pa14f_tcc0_wo4 */
#define PA14F_TCC0_WO4 \
	SAM_PINMUX(a, 14, f, periph)

/* pa14h_gclk_io0 */
#define PA14H_GCLK_IO0 \
	SAM_PINMUX(a, 14, h, periph)

/* pa15_gpio */
#define PA15_GPIO \
	SAM_PINMUX(a, 15, gpio, gpio)

/* pa15a_eic_extint15 */
#define PA15A_EIC_EXTINT15 \
	SAM_PINMUX(a, 15, a, periph)

/* pa15c_sercom2_pad3 */
#define PA15C_SERCOM2_PAD3 \
	SAM_PINMUX(a, 15, c, periph)

/* pa15d_sercom4_pad3 */
#define PA15D_SERCOM4_PAD3 \
	SAM_PINMUX(a, 15, d, periph)

/* pa15e_tc4_wo1 */
#define PA15E_TC4_WO1 \
	SAM_PINMUX(a, 15, e, periph)

/* pa15f_tcc0_wo5 */
#define PA15F_TCC0_WO5 \
	SAM_PINMUX(a, 15, f, periph)

/* pa15h_gclk_io1 */
#define PA15H_GCLK_IO1 \
	SAM_PINMUX(a, 15, h, periph)

/* pa16_gpio */
#define PA16_GPIO \
	SAM_PINMUX(a, 16, gpio, gpio)

/* pa16a_eic_extint0 */
#define PA16A_EIC_EXTINT0 \
	SAM_PINMUX(a, 16, a, periph)

/* pa16b_ptc_x4 */
#define PA16B_PTC_X4 \
	SAM_PINMUX(a, 16, b, periph)

/* pa16b_ptc_y20 */
#define PA16B_PTC_Y20 \
	SAM_PINMUX(a, 16, b, periph)

/* pa16c_sercom1_pad0 */
#define PA16C_SERCOM1_PAD0 \
	SAM_PINMUX(a, 16, c, periph)

/* pa16d_sercom3_pad0 */
#define PA16D_SERCOM3_PAD0 \
	SAM_PINMUX(a, 16, d, periph)

/* pa16e_tcc2_wo0 */
#define PA16E_TCC2_WO0 \
	SAM_PINMUX(a, 16, e, periph)

/* pa16f_tcc0_wo6 */
#define PA16F_TCC0_WO6 \
	SAM_PINMUX(a, 16, f, periph)

/* pa16h_gclk_io2 */
#define PA16H_GCLK_IO2 \
	SAM_PINMUX(a, 16, h, periph)

/* pa16i_ccl0_in0 */
#define PA16I_CCL0_IN0 \
	SAM_PINMUX(a, 16, i, periph)

/* pa17_gpio */
#define PA17_GPIO \
	SAM_PINMUX(a, 17, gpio, gpio)

/* pa17a_eic_extint1 */
#define PA17A_EIC_EXTINT1 \
	SAM_PINMUX(a, 17, a, periph)

/* pa17b_ptc_x5 */
#define PA17B_PTC_X5 \
	SAM_PINMUX(a, 17, b, periph)

/* pa17b_ptc_y21 */
#define PA17B_PTC_Y21 \
	SAM_PINMUX(a, 17, b, periph)

/* pa17c_sercom1_pad1 */
#define PA17C_SERCOM1_PAD1 \
	SAM_PINMUX(a, 17, c, periph)

/* pa17d_sercom3_pad1 */
#define PA17D_SERCOM3_PAD1 \
	SAM_PINMUX(a, 17, d, periph)

/* pa17e_tcc2_wo1 */
#define PA17E_TCC2_WO1 \
	SAM_PINMUX(a, 17, e, periph)

/* pa17f_tcc0_wo7 */
#define PA17F_TCC0_WO7 \
	SAM_PINMUX(a, 17, f, periph)

/* pa17h_gclk_io3 */
#define PA17H_GCLK_IO3 \
	SAM_PINMUX(a, 17, h, periph)

/* pa17i_ccl0_in1 */
#define PA17I_CCL0_IN1 \
	SAM_PINMUX(a, 17, i, periph)

/* pa18_gpio */
#define PA18_GPIO \
	SAM_PINMUX(a, 18, gpio, gpio)

/* pa18a_eic_extint2 */
#define PA18A_EIC_EXTINT2 \
	SAM_PINMUX(a, 18, a, periph)

/* pa18b_ptc_x6 */
#define PA18B_PTC_X6 \
	SAM_PINMUX(a, 18, b, periph)

/* pa18b_ptc_y22 */
#define PA18B_PTC_Y22 \
	SAM_PINMUX(a, 18, b, periph)

/* pa18c_sercom1_pad2 */
#define PA18C_SERCOM1_PAD2 \
	SAM_PINMUX(a, 18, c, periph)

/* pa18d_sercom3_pad2 */
#define PA18D_SERCOM3_PAD2 \
	SAM_PINMUX(a, 18, d, periph)

/* pa18e_tc4_wo0 */
#define PA18E_TC4_WO0 \
	SAM_PINMUX(a, 18, e, periph)

/* pa18f_tcc0_wo2 */
#define PA18F_TCC0_WO2 \
	SAM_PINMUX(a, 18, f, periph)

/* pa18h_ac_cmp0 */
#define PA18H_AC_CMP0 \
	SAM_PINMUX(a, 18, h, periph)

/* pa18i_ccl0_in2 */
#define PA18I_CCL0_IN2 \
	SAM_PINMUX(a, 18, i, periph)

/* pa19_gpio */
#define PA19_GPIO \
	SAM_PINMUX(a, 19, gpio, gpio)

/* pa19a_eic_extint3 */
#define PA19A_EIC_EXTINT3 \
	SAM_PINMUX(a, 19, a, periph)

/* pa19b_ptc_x7 */
#define PA19B_PTC_X7 \
	SAM_PINMUX(a, 19, b, periph)

/* pa19b_ptc_y23 */
#define PA19B_PTC_Y23 \
	SAM_PINMUX(a, 19, b, periph)

/* pa19c_sercom1_pad3 */
#define PA19C_SERCOM1_PAD3 \
	SAM_PINMUX(a, 19, c, periph)

/* pa19d_sercom3_pad3 */
#define PA19D_SERCOM3_PAD3 \
	SAM_PINMUX(a, 19, d, periph)

/* pa19e_tc4_wo1 */
#define PA19E_TC4_WO1 \
	SAM_PINMUX(a, 19, e, periph)

/* pa19f_tcc0_wo3 */
#define PA19F_TCC0_WO3 \
	SAM_PINMUX(a, 19, f, periph)

/* pa19h_ac_cmp1 */
#define PA19H_AC_CMP1 \
	SAM_PINMUX(a, 19, h, periph)

/* pa19i_ccl0_out0 */
#define PA19I_CCL0_OUT0 \
	SAM_PINMUX(a, 19, i, periph)

/* pa22_gpio */
#define PA22_GPIO \
	SAM_PINMUX(a, 22, gpio, gpio)

/* pa22a_eic_extint6 */
#define PA22A_EIC_EXTINT6 \
	SAM_PINMUX(a, 22, a, periph)

/* pa22b_ptc_x10 */
#define PA22B_PTC_X10 \
	SAM_PINMUX(a, 22, b, periph)

/* pa22b_ptc_y26 */
#define PA22B_PTC_Y26 \
	SAM_PINMUX(a, 22, b, periph)

/* pa22c_sercom3_pad0 */
#define PA22C_SERCOM3_PAD0 \
	SAM_PINMUX(a, 22, c, periph)

/* pa22d_sercom5_pad0 */
#define PA22D_SERCOM5_PAD0 \
	SAM_PINMUX(a, 22, d, periph)

/* pa22e_tc0_wo0 */
#define PA22E_TC0_WO0 \
	SAM_PINMUX(a, 22, e, periph)

/* pa22f_tcc0_wo4 */
#define PA22F_TCC0_WO4 \
	SAM_PINMUX(a, 22, f, periph)

/* pa22h_gclk_io6 */
#define PA22H_GCLK_IO6 \
	SAM_PINMUX(a, 22, h, periph)

/* pa22i_ccl2_in6 */
#define PA22I_CCL2_IN6 \
	SAM_PINMUX(a, 22, i, periph)

/* pa23_gpio */
#define PA23_GPIO \
	SAM_PINMUX(a, 23, gpio, gpio)

/* pa23a_eic_extint7 */
#define PA23A_EIC_EXTINT7 \
	SAM_PINMUX(a, 23, a, periph)

/* pa23b_ptc_x11 */
#define PA23B_PTC_X11 \
	SAM_PINMUX(a, 23, b, periph)

/* pa23b_ptc_y27 */
#define PA23B_PTC_Y27 \
	SAM_PINMUX(a, 23, b, periph)

/* pa23c_sercom3_pad1 */
#define PA23C_SERCOM3_PAD1 \
	SAM_PINMUX(a, 23, c, periph)

/* pa23d_sercom5_pad1 */
#define PA23D_SERCOM5_PAD1 \
	SAM_PINMUX(a, 23, d, periph)

/* pa23e_tc0_wo1 */
#define PA23E_TC0_WO1 \
	SAM_PINMUX(a, 23, e, periph)

/* pa23f_tcc0_wo5 */
#define PA23F_TCC0_WO5 \
	SAM_PINMUX(a, 23, f, periph)

/* pa23h_gclk_io7 */
#define PA23H_GCLK_IO7 \
	SAM_PINMUX(a, 23, h, periph)

/* pa23i_ccl2_in7 */
#define PA23I_CCL2_IN7 \
	SAM_PINMUX(a, 23, i, periph)

/* pa24_gpio */
#define PA24_GPIO \
	SAM_PINMUX(a, 24, gpio, gpio)

/* pa24a_eic_extint12 */
#define PA24A_EIC_EXTINT12 \
	SAM_PINMUX(a, 24, a, periph)

/* pa24c_sercom3_pad2 */
#define PA24C_SERCOM3_PAD2 \
	SAM_PINMUX(a, 24, c, periph)

/* pa24d_sercom5_pad2 */
#define PA24D_SERCOM5_PAD2 \
	SAM_PINMUX(a, 24, d, periph)

/* pa24e_tc1_wo0 */
#define PA24E_TC1_WO0 \
	SAM_PINMUX(a, 24, e, periph)

/* pa24f_tcc1_wo2 */
#define PA24F_TCC1_WO2 \
	SAM_PINMUX(a, 24, f, periph)

/* pa24h_ac_cmp2 */
#define PA24H_AC_CMP2 \
	SAM_PINMUX(a, 24, h, periph)

/* pa24i_ccl2_in8 */
#define PA24I_CCL2_IN8 \
	SAM_PINMUX(a, 24, i, periph)

/* pa25_gpio */
#define PA25_GPIO \
	SAM_PINMUX(a, 25, gpio, gpio)

/* pa25a_eic_extint13 */
#define PA25A_EIC_EXTINT13 \
	SAM_PINMUX(a, 25, a, periph)

/* pa25c_sercom3_pad3 */
#define PA25C_SERCOM3_PAD3 \
	SAM_PINMUX(a, 25, c, periph)

/* pa25d_sercom5_pad3 */
#define PA25D_SERCOM5_PAD3 \
	SAM_PINMUX(a, 25, d, periph)

/* pa25e_tc1_wo1 */
#define PA25E_TC1_WO1 \
	SAM_PINMUX(a, 25, e, periph)

/* pa25f_tcc1_wo3 */
#define PA25F_TCC1_WO3 \
	SAM_PINMUX(a, 25, f, periph)

/* pa25h_ac_cmp3 */
#define PA25H_AC_CMP3 \
	SAM_PINMUX(a, 25, h, periph)

/* pa25i_ccl2_out2 */
#define PA25I_CCL2_OUT2 \
	SAM_PINMUX(a, 25, i, periph)

/* pa27_gpio */
#define PA27_GPIO \
	SAM_PINMUX(a, 27, gpio, gpio)

/* pa27a_eic_extint15 */
#define PA27A_EIC_EXTINT15 \
	SAM_PINMUX(a, 27, a, periph)

/* pa27h_gclk_io0 */
#define PA27H_GCLK_IO0 \
	SAM_PINMUX(a, 27, h, periph)

/* pa28_gpio */
#define PA28_GPIO \
	SAM_PINMUX(a, 28, gpio, gpio)

/* pa28a_eic_extint8 */
#define PA28A_EIC_EXTINT8 \
	SAM_PINMUX(a, 28, a, periph)

/* pa28h_gclk_io0 */
#define PA28H_GCLK_IO0 \
	SAM_PINMUX(a, 28, h, periph)

/* pa30_gpio */
#define PA30_GPIO \
	SAM_PINMUX(a, 30, gpio, gpio)

/* pa30a_eic_extint10 */
#define PA30A_EIC_EXTINT10 \
	SAM_PINMUX(a, 30, a, periph)

/* pa30d_sercom1_pad2 */
#define PA30D_SERCOM1_PAD2 \
	SAM_PINMUX(a, 30, d, periph)

/* pa30e_tcc1_wo0 */
#define PA30E_TCC1_WO0 \
	SAM_PINMUX(a, 30, e, periph)

/* pa30g_swd_clk */
#define PA30G_SWD_CLK \
	SAM_PINMUX(a, 30, g, periph)

/* pa30h_gclk_io0 */
#define PA30H_GCLK_IO0 \
	SAM_PINMUX(a, 30, h, periph)

/* pa30i_ccl1_in3 */
#define PA30I_CCL1_IN3 \
	SAM_PINMUX(a, 30, i, periph)

/* pa31_gpio */
#define PA31_GPIO \
	SAM_PINMUX(a, 31, gpio, gpio)

/* pa31a_eic_extint11 */
#define PA31A_EIC_EXTINT11 \
	SAM_PINMUX(a, 31, a, periph)

/* pa31d_sercom1_pad3 */
#define PA31D_SERCOM1_PAD3 \
	SAM_PINMUX(a, 31, d, periph)

/* pa31e_tcc1_wo1 */
#define PA31E_TCC1_WO1 \
	SAM_PINMUX(a, 31, e, periph)

/* pa31g_swd_io */
#define PA31G_SWD_IO \
	SAM_PINMUX(a, 31, g, periph)

/* pa31i_ccl1_out1 */
#define PA31I_CCL1_OUT1 \
	SAM_PINMUX(a, 31, i, periph)
